### ISSUE TITLE
1.4.0+ Changes

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [MaxNeedsSnacks/Skys-The-Limit#10]
- [x] Adjust ExU Furnace Generator recipe (it's a bit ridiculous, honestly.)
- [x] (Slightly) buff the Hardened Casing recipe
- [x] Buff Squeezer Seed Oil output
- [x] Re-enable Atomic Reconstructor Prismarine recipe
- [x] Tweak the numbers on various configs a bit
- [x] Balance EnderIO recipes a tad
- [x] Rework Electrotine recipe.
- [x] Buff Sky Stone a lot because holy heck Sky Resources made that recipe difficult.
- [x] Reintroduce more stuff I've removed for balance reasons.

**Comment by NarigudoBR** [comment]
a way to get prosperity shard?

**Comment by MaxNeedsSnacks** [comment]
There's some weird issue with Thermal Expansion and JEI going on right now, I think I'll have to defer this update for a while since the holidays are coming up.
