### ISSUE TITLE
Possible nerf for redstone -> glowstone botania recipe?

### ISSUE THREAD

**Issue by NarigudoBR** [MaxNeedsSnacks/Skys-The-Limit#12]
Is it going to be nerfed?

**Comment by MaxNeedsSnacks** [comment]
I'm honestly not 100% sure about it, but I've definitely just... forgotten to nerf the Alchemy Catalyst recipe. That'll probably be a thing for 1.4.0.

**Comment by NarigudoBR** [comment]
nerfing the mana cost may be a good idea, also the recipe for the catalyst could be changed(requiring more complex stuff)
