### ISSUE TITLE
Hopper

### ISSUE THREAD

**Issue by motivo** [MaxNeedsSnacks/Skys-The-Limit#6]
I really can't find  a way to create a hopper from the "Wooper Mod". The recipe creates only wooden hopper from Tinkers' and this one doesn't work in the recipe for a vanilla hopper.

**Comment by MaxNeedsSnacks** [comment]
The update's currently under review on CurseForge. Until then, feel free to add `recipes.remove(<tconstruct:wooden_hopper>);` to the recipes.zs file in the /scripts/ folder. Just remember to remove it once the new update's been approved ^^

**Comment by MaxNeedsSnacks** [comment]
Closed as of the release of 1.2.1a
